name: Create Release

on:
  push:
    branches:
      - production # This workflow triggers when commits are pushed to production

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: production
          default_bump: minor # Automatically increments the minor version. Change this to major, minor, or patch as needed.
          create_annotated_tag: true # Creates an annotated tag, which is recommended for most use cases.
          # Optional: If you want to use a specific versioning scheme or customize tag creation further, you can add additional configuration here.

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
            Changes in this Release
            - First version of the release
          draft: false
          prerelease: false
